
DROP SEQUENCE SIMPLE_CLASSES_ID_SEQ;

CREATE SEQUENCE SIMPLE_CLASSES_ID_SEQ INCREMENT BY 1 START WITH 1;

DROP TABLE SIMPLE_CLASSES CASCADE CONSTRAINTS;

CREATE TABLE SIMPLE_CLASSES 
(
  ID INTEGER NOT NULL 
, NAME VARCHAR2(50) 
, CONSTRAINT SIMPLE_CLASSES_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

create or replace trigger ON_SIMPLE_CLASSES_INSERT
	before insert on SIMPLE_CLASSES
	for each row
	begin
	if :new.ID is null then
		select SIMPLE_CLASSES_ID_SEQ.nextval into :new.ID from dual;
	end if;
	end;
	/